version: "3.8"
services:
    mongo:
        image: mongo:5.0
        container_name: mongo
        env_file:
            - .env
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
        restart: unless-stopped
        ports:
            - "27017:27017"
        volumes:
            - ./database/db:/data/db # mongodb 데이터 저장
        networks:
            - ajangnet1
    front:
        image: momnpa333/ajangfront:latest
        container_name: mreact
        ports:
            - "5173:5173"
        networks:
            - ajangfront
    back:
        image: momnpa333/ajangback:latest
        container_name: mexpress
        env_file:
            - .env
        depends_on:
            - mongo
        environment:
            - MONGO_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@mongo:27017
        restart: unless-stopped
        ports:
            - "8080:8080"
        networks:
            - ajangnet1
        healthcheck: #db가 연결할 준비가 되었는지 체크
            test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
            interval: 10s
            timeout: 5s
            retries: 10
networks:
    ajangnet1:
        driver: bridge
    ajangfront:
        driver: bridge
